global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Contact Center API metrics
  - job_name: "contact-center-api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis monitoring (eliminado)

  # PostgreSQL monitoring (if postgres_exporter is added)
  # - job_name: "postgres"
  #   static_configs:
  #     - targets: ["postgres_exporter:9187"]
