name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Quick validation
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check Python syntax
        run: |
          python -m py_compile app/**/*.py config/**/*.py tests/**/*.py || true
          find . -name "*.py" -not -path "./venv/*" -not -path "./.venv/*" | xargs python -m py_compile

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

  # Run tests
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        env:
          PYTHONPATH: "."
          DISABLE_DB: "true"
          SECRET_KEY: "test-secret-key-for-ci-only"
          ARI_HTTP_URL: "http://test-asterisk:8088/ari"
          ARI_USERNAME: "test"
          ARI_PASSWORD: "test"
        run: |
          pytest tests/ -v --tb=short

  # Build Docker image (don't push)
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: contact-center-api:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
